### ISSUE TITLE
Keep getting java.lang.IndexOutofBoundsException

### ISSUE THREAD

**Issue by esokullu** [teaddict/turkce-metin-ozetleme#1]
with the simple /api/new?contextOfText={some_short_text}

Using Tomcat 8 on Ubuntu 16.04. Also tried with Tomcat 7 and no luck. JDK: OpenJDK 8 (with memory settings finetuned properly)

Please advise.

**Comment by esokullu** [comment]
This is the URL btw: http://83.149.67.213:8080/turkcemetinozetleme-0.0.1-SNAPSHOT/api/new

**Comment by teaddict** [comment]
Hi @esokullu , 
Can you try like this https://github.com/teaddict/teaddict-net/blob/master/ozetle/turkce-metin-ozetleme.html
with this examples https://github.com/teaddict/turkce-metin-ozetleme/tree/master/ornek-metinler . Because they are my test set, if they don't work , I will check it again, I have [my own server](http://teaddict.net/ozetle/summarize.html) which is running latest version and there is not any problem. If you still have problems, can you please share your test data here :)

**Comment by teaddict** [comment]
I tried your service , and it works actually:
I use Firefox with this addon https://addons.mozilla.org/en-US/firefox/addon/httprequester/
After opening addon , I gave your service url, then I clicked parameters and 
Name: contextOfText
Value:  "Türkiye Yaş Meyve ve Sebze İhracatçı Birliklerinden yapılan yazılı açıklamada, "Rusya Federasyonu'nun Türkiye'den sadece 4 firmaya domates ihracatı için izin vermesi kararını kesinlikle kabul etmiyoruz." ifadesi kullanıldı.  Rusya Federasyonu’nun bu kısıtlamasının sektörde tekelleşmeye ve haksız rekabete sebep olacağı savunulan açıklamada şunlar kaydedildi:  "Uygulama, yaş meyve sebze sektörü ihracatına ve ihracatçısına büyük zararlar verecektir. Ayrıca, bu uygulama üreticiler üzerinde kartel oluşturacak ve üreticilerimiz, ürünlerini ucuz fiyattan satmak zorunda bırakılacaktır. Tek taraflı olarak belirlenen ve hangi temel ve kritere dayandırıldığı açıklanmayan firma seçimleri, sektöre hiçbir katkı yapmayacak ve gayri resmi uygulama alışkanlıklarının da doğmasına sebebiyet vererek hem ihracatçıların hem de üreticilerin büyük mağduriyet yaşamasına neden olacaktır."  Türkiye'nin yaş meyve ve sebze üretiminin dünya standartlarının üzerinde olduğu vurgulanarak, "İnsan ve çevre sağlığı odaklı üretim yapan üreticilerimiz, üretim alanlarında tarım teknolojilerinin bütün imkanlarından yararlanarak Ekonomi Bakanlığı ve Gıda, Tarım ve Hayvancılık Bakanlığı ile iş birliği içinde büyük başarılara imza atmıştır. Birlik olarak sektörde önü alınamayacak zararlara sebebiyet vermemesi açısından Rusya Federasyonu’na ihraç edilecek tüm ürünlerde tüm firmalara kısıtlama olmadan izin verilmesini talep ediyoruz."

then click POST and it returns summary.

![summary](https://user-images.githubusercontent.com/4656439/32051586-db5c3528-ba5d-11e7-8026-274fcf99f2e3.png)

**Comment by esokullu** [comment]
Thank you. 

I've just found the problem. When there is no punctuation, not even a single dot, try the following:

* http --form POST "http://83.149.67.213:8080/turkcemetinozetleme-0.0.1-SNAPSHOT/api/new" contextOfText="ben bir deneme aletiyim"

* http --form POST "http://83.149.67.213:8080/turkcemetinozetleme-0.0.1-SNAPSHOT/api/new" contextOfText="ben bir deneme aletiyim."

The former gives 500 Internal Server Error with java.lang.IndexOutOfBoundsException, the latter works.

**Comment by esokullu** [comment]
It doesn't make sense to use a summarizer for such a short sentence though, so you may ignore :)

**Comment by teaddict** [comment]
Yes it is known issue. App expects grammatically correct text :)
